#!/bin/sh
. "$(dirname "$0")/_/husky.sh"
. "$(dirname "$0")/common.sh"

[ -n "$CI" ] && exit 0

PATH="/usr/local/bin:$PATH"

echo 'Running Git Hooks'
echo "🔎... Checking validity of types with TypeScript"

pnpm type-check || (
    "⛔️ There is a type error in your code, fix it first, and try commit again. ⛔️";
    false;
)

echo "✅ No TypeError found"
echo "⌛️ Running lint staged and git commit ⌛️"

# Format and submit code according to lintstagedrc.js configuration
pnpm exec lint-staged